// Global CSS
import './globals.css';

// Meta data
import type { Metadata } from 'next';

// Google fonts
import { Kanit } from 'next/font/google';

// Components
import Navigation from './components/layout/Navigation';
import Footer from './components/layout/Footer';
import Head from 'next/head';



// Fonts
const kanit = Kanit({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

// Meta data
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-CELKBJZVJM" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${process.env.NEX_PUBLIC_GOOGLE_ANALYTICS}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
      </Head>
      <body className={`${kanit.className}`}>
        <div id="container">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
