// Global CSS
import './globals.css';

// Meta data
import type { Metadata } from 'next';

// Google fonts
import { Kanit } from 'next/font/google';

// Components
import Footer from './components/layout/Footer';



// Fonts
const kanit = Kanit({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

// Meta data
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
